<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class SocialNetwork extends Model
{
    protected $fillable = [
        'title',
        'url',
        'icon',
    ];

    public function delete()
    {
        deleteStorageFile($this->icon);
        parent::delete(); // TODO: Change the autogenerated stub
        return true;
    }
}
